"""Self-contained diagnostic report for paired matches."""
from __future__ import annotations
import json
from statistics import median


def summarize(runs):
    result = {}
    baselines = {r.get("seed"): r for r in runs if r.get("scenario") == "baseline" and r.get("outcome") in ("win", "timeout")}
    for name in sorted({r["scenario"] for r in runs}):
        items = [r for r in runs if r["scenario"] == name]
        valid = [r for r in items if r.get("outcome") in ("win", "timeout")]
        wins = sum(r.get("winning_team_id") == r.get("candidate_team") for r in valid if r["outcome"] == "win")
        money_delta = [r["timeline"][-1]["teams"][0]["money"] - r["timeline"][0]["teams"][0]["money"] for r in valid if r.get("timeline")]
        pairs = [(r, baselines[r["seed"]]) for r in valid if r.get("scenario") != "baseline" and r.get("seed") in baselines]
        result[name] = {"runs": len(items), "technical_failures": len(items)-len(valid), "wins": wins, "win_rate": wins/len(valid) if valid else None, "timeouts": sum(r["outcome"] == "timeout" for r in valid), "stalls": sum(r.get("first_king_damage", -1) < 0 for r in valid), "median_duration": median(r["duration"] for r in valid) if valid else None, "median_first_king_damage": median(r["first_king_damage"] for r in valid if r.get("first_king_damage", -1) >= 0) if any(r.get("first_king_damage", -1) >= 0 for r in valid) else None, "median_team1_money_delta": median(money_delta) if money_delta else None, "paired_runs": len(pairs), "median_paired_duration_delta": median(r["duration"]-b["duration"] for r,b in pairs) if pairs else None, "paired_win_delta": sum((r.get("winning_team_id") == r["candidate_team"]) - (b.get("winning_team_id") == r["candidate_team"]) for r,b in pairs) if pairs else None}
    return result


def html_report(report):
    payload = json.dumps(report, separators=(",", ":")).replace("<", "\\u003c")
    return '''<!doctype html><html lang="en"><meta charset="utf-8"><title>Match balance lab</title>
<style>body{font:15px system-ui;background:#101828;color:#edf2fa;margin:2rem;max-width:1100px}h1,h2{color:#fff}table{border-collapse:collapse;width:100%}td,th{padding:.5rem;border-bottom:1px solid #334;text-align:left}select,input,button{margin:.4rem;background:#263750;color:white;border:1px solid #567;padding:.35rem}canvas{background:#142339;width:100%;max-width:920px;border:1px solid #567}.bar{background:#4db5dc;height:1rem}</style>
<h1>Match balance lab</h1><p>Diagnostic evidence only. Paired seeds reduce random variation; small batches do not establish a balance verdict. The focus side is team 1 for shared changes and the modified team for asymmetric changes.</p><h2>Comparison</h2><div id="summary"></div><h2>Strategic replay</h2><select id="run"></select><button id="play">Play</button><label>Speed <select id="speed"><option>1</option><option>2</option><option>4</option><option>8</option></select></label><label><input type="checkbox" id="team1" checked>Azure</label><label><input type="checkbox" id="team2" checked>Ember</label><br><input id="seek" type="range" min="0" value="0" style="width:80%"><span id="clock"></span><br><canvas id="map" width="920" height="520"></canvas><h2>Economy trend</h2><p>Money (solid) and wood (dashed) by team</p><canvas id="economy" width="920" height="240"></canvas><h2>Events</h2><div id="events"></div><h2>Run details</h2><pre id="details"></pre>
<script id="payload" type="application/json">''' + payload + '''</script><script>const data=JSON.parse(document.getElementById('payload').textContent), runs=data.runs, sel=document.getElementById('run'), seek=document.getElementById('seek'),ctx=document.getElementById('map').getContext('2d');let playing=false,last=0;
const summary=document.getElementById('summary');summary.innerHTML='<table><tr><th>Scenario</th><th>Runs</th><th>Focus wins</th><th>Win rate</th><th>Median duration</th><th>Paired duration Δ</th><th>Paired win Δ</th><th>Timeouts</th><th>Stalls</th><th>Team 1 money Δ</th><th>Failures</th></tr>'+Object.entries(data.summary).map(([n,s])=>`<tr><td>${escapeHtml(n)}</td><td>${s.runs}</td><td>${s.wins}</td><td><div class="bar" style="width:${100*(s.win_rate||0)}%"></div>${s.win_rate===null?'—':(100*s.win_rate).toFixed(0)+'%'}</td><td>${s.median_duration===null?'—':s.median_duration.toFixed(1)+'s'}</td><td>${s.median_paired_duration_delta===null?'—':s.median_paired_duration_delta.toFixed(1)+'s'}</td><td>${s.paired_win_delta??'—'}</td><td>${s.timeouts}</td><td>${s.stalls}</td><td>${s.median_team1_money_delta??'—'}</td><td>${s.technical_failures}</td></tr>`).join('')+'</table>';
function escapeHtml(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}runs.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${r.scenario} / seed ${r.seed} / ${r.assignment}`;sel.append(o)});
function draw(){const r=runs[+sel.value];if(!r||!r.timeline?.length)return;seek.max=r.timeline.length-1;const s=r.timeline[+seek.value]||r.timeline[0];ctx.clearRect(0,0,920,520);ctx.fillStyle='#284057';ctx.fillRect(0,0,920,520);ctx.strokeStyle='#758598';ctx.strokeRect(30,30,860,460);for(const e of s.entities){if(!document.getElementById('team'+e[0]).checked)continue;const color=e[0]===1?'#50c5ff':'#ff7969';ctx.fillStyle=color;const radius=e[1]==='king'?12:e[1]==='tower'?8:e[1]==='player'?6:3;ctx.beginPath();ctx.arc(e[2]/5,e[3]/5,radius,0,7);ctx.fill()}document.getElementById('clock').textContent=`${s.t.toFixed(1)} / ${r.duration.toFixed(1)} s`;document.getElementById('events').innerHTML=(r.events||[]).filter(e=>e.t<=s.t).slice(-12).map(e=>`<div>${e.t.toFixed(1)}s: ${escapeHtml(e.type)} · team ${e.team}</div>`).join('');document.getElementById('details').textContent=JSON.stringify({outcome:r.outcome,winner:r.winning_team_id,teams:s.teams,config:r.effective_config},null,2)}
function economy(){const r=runs[+sel.value],c=document.getElementById('economy').getContext('2d');c.clearRect(0,0,920,240);if(!r?.timeline?.length)return;const values=r.timeline.flatMap(s=>s.teams.flatMap(t=>[t.money,t.wood])),top=Math.max(100,...values);for(const team of [0,1])for(const key of ['money','wood']){c.beginPath();c.strokeStyle=team===0?'#50c5ff':'#ff7969';c.setLineDash(key==='wood'?[5,4]:[]);r.timeline.forEach((s,i)=>{const x=20+880*i/Math.max(1,r.timeline.length-1),y=220-200*s.teams[team][key]/top;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()}c.setLineDash([])}
sel.onchange=()=>{seek.value=0;draw();economy()};seek.oninput=draw;team1.onchange=draw;team2.onchange=draw;play.onclick=()=>{playing=!playing;play.textContent=playing?'Pause':'Play'};function tick(t){if(playing&&t-last>500/+speed.value){seek.value=(+seek.value+1)%(+seek.max+1);draw();last=t}requestAnimationFrame(tick)}draw();economy();requestAnimationFrame(tick);</script>
</html>'''
